const $=(selector,root=document)=>root.querySelector(selector),$$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const app=$('#app'),cfg=window.GRAVITY58_AD_BOOKING_CONFIG||{},api=window.Gravity58Ads;
const now=()=>new Date().toISOString(),money=value=>`₹${Number(value||0).toLocaleString('en-IN')}`;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const slots=[
  {id:'right_rail',name:'Right Vertical Menu Ad',description:'Always-visible vertical placement beside the restaurant menu.',rate:120},
  {id:'preparing',name:'Food Preparing Screen',description:'Promotion while customers follow order preparation.',rate:80},
  {id:'thankyou',name:'Thank You Screen',description:'Promotion after a completed restaurant order.',rate:60},
];
const samples=[
  {style:'flash',title:'FLASH SALE',description:'Today only · Save 25%',tone:'orange'},
  {style:'pulse',title:'NEW ARRIVAL',description:'Tap to discover the launch',tone:'red'},
  {style:'spotlight',title:'LOCAL FAVOURITE',description:'Fresh offers near you',tone:'gold'},
];
let user=null,profile=null,creativeDraft=null;

function toast(message){const target=$('#toast');target.textContent=message;target.classList.add('show');setTimeout(()=>target.classList.remove('show'),2600)}
function restaurantParam(){return new URLSearchParams(location.search).get('restaurant')||''}
function statusClass(status){return status==='Live'?'live':status==='Rejected'?'rejected':'pending'}
function timeLeft(expiresAt){const ms=new Date(expiresAt)-new Date();if(ms<=0)return'Expired';const days=Math.floor(ms/864e5),hours=Math.floor(ms%864e5/36e5),minutes=Math.floor(ms%36e5/6e4);return`${days?days+'d ':''}${hours}h ${minutes}m remaining`}
function mediaMarkup(record,className='creative-media'){
  const src=record.mediaUrl||record.proofMediaUrl||'';
  if(!src)return`<div class="creative-placeholder ${esc(record.creativeStyle||'spotlight')}"><b>${esc(record.title||'YOUR AD')}</b><small>${esc(record.description||'Upload an image, GIF or video')}</small></div>`;
  if(/^video\//.test(record.mediaType||'')||/\.(mp4|webm)(\?|$)/i.test(src))return`<video class="${className}" src="${esc(src)}" autoplay muted loop playsinline controls></video>`;
  return`<img class="${className}" src="${esc(src)}" alt="${esc(record.title||'Advertisement creative')}">`;
}
function modal(title,body,ready){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><section class="card modal-card"><div class="topbar"><h2>${esc(title)}</h2><button class="btn secondary" id="closeModal" type="button" aria-label="Close dialog">✕</button></div>${body}</section></div>`);$('#closeModal').onclick=closeModal;ready?.()}
function closeModal(){$('#modal')?.remove()}

async function boot(){user=await api.currentUser();if(user){profile=(await api.list('profiles',{userId:user.$id}))[0]||{name:user.name,email:user.email};await dashboard()}else auth()}
function auth(){app.innerHTML=`<main class="screen auth"><section class="card auth-card"><a href="../" class="back-link">← G58 Home</a><div class="brand"><div class="mark">G</div><div><h2>Gravity58 Ad Booking</h2><p class="muted">Create, reserve and track Digital Menu advertising.</p></div></div><div class="actions auth-actions"><button class="btn" id="showLogin">Login</button><button class="btn secondary" id="showRegister">Create Account</button><button class="btn secondary" id="showForgot">Forgot Password</button></div><div id="authBox"></div>${!api.configured?'<div class="notice">Account services are temporarily unavailable. Please try again shortly.</div>':''}</section></main>`;$('#showLogin').onclick=loginForm;$('#showRegister').onclick=registerForm;$('#showForgot').onclick=forgotForm;loginForm()}
function loginForm(){$('#authBox').innerHTML=`<form id="login"><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Password</label><input name="password" type="password" minlength="8" required></div><button class="btn full">Login</button></form>`;$('#login').onsubmit=async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));try{await api.login(data.email,data.password);await boot()}catch(error){toast(error.message||'Login failed')}}}
function registerForm(){$('#authBox').innerHTML=`<form id="register"><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Phone number</label><input name="phone" inputmode="tel" required></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Password</label><input name="password" type="password" minlength="8" required></div><button class="btn full">Create Account</button></form>`;$('#register').onsubmit=async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));try{await api.register(data.email,data.password,data.name,data.phone);toast('Account created successfully');await boot()}catch(error){toast(error.message||'Account creation failed')}}}
function forgotForm(){$('#authBox').innerHTML=`<form id="forgotForm"><div class="field"><label>Registered email</label><input name="email" type="email" required></div><button class="btn full">Send reset link</button></form>`;$('#forgotForm').onsubmit=async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));try{await api.forgotPassword(data.email,location.origin+'/reset-password/');toast('Password reset link sent successfully')}catch(error){toast(error.message||'Could not send reset link')}}}

async function dashboard(){
  const mine=(await api.list('bookings',{customerId:user.$id})).sort((a,b)=>new Date(b.$createdAt||b.createdAt)-new Date(a.$createdAt||a.createdAt));
  const current=mine.filter(row=>row.status==='Live'&&(!row.expiresAt||new Date(row.expiresAt)>new Date()));
  const history=mine.filter(row=>!current.includes(row));
  app.innerHTML=`<main class="shell"><header class="topbar"><div class="brand"><div class="mark">G</div><div><h2>Gravity58 Ad Booking</h2><p class="muted">Welcome, ${esc(profile?.name||user.name||user.email)}</p></div></div><div class="actions"><a class="btn secondary" href="../">G58 Home</a><button class="btn secondary" id="creativeStudio">Creative Studio</button><button class="btn" id="newBooking">Book Ad Space</button><button class="btn secondary" id="logout">Logout</button></div></header><section class="grid stats">${metric('Requests',mine.length)}${metric('Awaiting Payment',mine.filter(row=>row.status==='Payment Link Sent').length)}${metric('Under Review',mine.filter(row=>row.status==='Proof Sent').length)}${metric('Live Ads',current.length)}</section><h2 style="margin-top:28px">Current Advertisements</h2><section class="grid booking-grid">${current.map(bookingCard).join('')||'<article class="card"><p class="muted">No advertisement is currently live.</p></article>'}</section><h2 style="margin-top:28px">Advertising History</h2><section class="grid booking-grid">${history.map(bookingCard).join('')||'<article class="card"><p class="muted">No previous advertising requests.</p></article>'}</section></main>`;
  $('#logout').onclick=async()=>{await api.logout();user=null;profile=null;auth()};
  $('#newBooking').onclick=()=>bookingWizard();$('#creativeStudio').onclick=creativeStudio;bindBookingActions();
}
function metric(title,value){return`<article class="card metric"><span class="muted">${title}</span><strong>${value}</strong></article>`}
function bookingCard(booking){
  const slot=slots.find(row=>row.id===booking.slotId);let action='';
  if(booking.status==='Payment Link Sent')action=`<a class="btn" href="${esc(booking.paymentLink)}" target="_blank" rel="noopener">Pay Now</a><button class="btn secondary" data-proof="${booking.id}">Submit Payment Proof</button>`;
  if(booking.status==='Proof Sent')action='<span class="notice compact-notice">Payment submitted for admin verification.</span>';
  if(booking.status==='Live')action=`<a class="btn" href="${esc(booking.destinationUrl||'#')}" target="_blank" rel="noopener">View Destination</a>`;
  return`<article class="card booking-card"><div class="booking-creative">${mediaMarkup(booking)}</div><div class="topbar booking-title"><h3>${esc(booking.title||slot?.name||booking.slotId)}</h3><span class="status ${statusClass(booking.status)}">${esc(booking.status)}</span></div><p class="muted">${esc(slot?.name||booking.slotId)}</p><p><strong>${esc(booking.restaurantKey)}</strong></p><p class="muted">${booking.hours} hour(s) · ${money(booking.amount)}</p>${booking.paymentReference?`<p><strong>Payment reference:</strong> ${esc(booking.paymentReference)}</p>`:''}${booking.adminMessage?`<div class="notice">${esc(booking.adminMessage)}</div>`:''}${booking.expiresAt?`<div class="notice"><strong>Expires:</strong> ${new Date(booking.expiresAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}<p class="ad-countdown" data-expires="${booking.expiresAt}" style="margin:8px 0 0"><strong>${timeLeft(booking.expiresAt)}</strong></p></div>`:''}<div class="actions" style="margin-top:14px">${action}</div></article>`;
}
function bindBookingActions(){$$('[data-proof]').forEach(button=>button.onclick=()=>paymentProofDialog(button.dataset.proof))}

function creativeStudio(){
  const draft=creativeDraft||samples[0];
  app.innerHTML=`<main class="shell"><header class="topbar"><div><h1>Advertisement Creative Studio</h1><p class="muted">Start with a sample, add your message and use it in a booking.</p></div><button class="btn secondary" id="back">Back</button></header><section class="studio-layout"><div class="card"><h2>1. Choose an animated style</h2><div class="sample-grid">${samples.map(sample=>`<button class="sample-ad ${sample.style===draft.creativeStyle||sample.style===draft.style?'selected':''} creative-${sample.style}" type="button" data-sample="${sample.style}"><b>${sample.title}</b><small>${sample.description}</small></button>`).join('')}</div><div class="field"><label>Advertisement title</label><input id="studioTitle" value="${esc(draft.title||'')}"></div><div class="field"><label>Description</label><textarea id="studioDescription">${esc(draft.description||'')}</textarea></div><div class="field"><label>Destination URL</label><input id="studioDestination" type="url" value="${esc(draft.destinationUrl||'https://g58.in/')}"></div><div class="field"><label>Creative image, animated GIF or video</label><input id="studioMedia" type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm"><small class="muted">Maximum 15 MB. JPG, PNG, WebP, GIF, MP4 or WebM.</small></div><button class="btn full" id="useCreative">Use Creative in Booking</button></div><aside class="card studio-preview"><p class="muted">LIVE PREVIEW</p><div id="creativePreview" class="ad-preview creative-${esc(draft.creativeStyle||draft.style||'flash')}">${draft.mediaUrl?mediaMarkup(draft):`<div class="creative-placeholder"><b>${esc(draft.title||'FLASH SALE')}</b><small>${esc(draft.description||'Today only')}</small></div>`}</div></aside></section></main>`;
  let style=draft.creativeStyle||draft.style||'flash',mediaFile=null,localUrl=draft.mediaUrl||'';
  const draw=()=>{$('#creativePreview').className=`ad-preview creative-${style}`;$('#creativePreview').innerHTML=localUrl?mediaMarkup({mediaUrl:localUrl,mediaType:mediaFile?.type||draft.mediaType,title:$('#studioTitle').value}):`<div class="creative-placeholder"><b>${esc($('#studioTitle').value||'YOUR AD')}</b><small>${esc($('#studioDescription').value||'Add your offer')}</small></div>`};
  $$('[data-sample]').forEach(button=>button.onclick=()=>{style=button.dataset.sample;$$('[data-sample]').forEach(x=>x.classList.toggle('selected',x===button));const sample=samples.find(x=>x.style===style);$('#studioTitle').value=sample.title;$('#studioDescription').value=sample.description;draw()});
  $('#studioMedia').onchange=event=>{mediaFile=event.target.files[0]||null;if(mediaFile){try{api.validateMediaFile?.(mediaFile)}catch(error){event.target.value='';mediaFile=null;return toast(error.message)}localUrl=URL.createObjectURL(mediaFile)}draw()};
  $('#studioTitle').oninput=draw;$('#studioDescription').oninput=draw;$('#back').onclick=dashboard;
  $('#useCreative').onclick=()=>{const title=$('#studioTitle').value.trim(),description=$('#studioDescription').value.trim();if(!title||!description)return toast('Add a title and description');creativeDraft={title,description,destinationUrl:$('#studioDestination').value.trim(),creativeStyle:style,mediaFile,mediaUrl:mediaFile?localUrl:(draft.mediaUrl||''),mediaType:mediaFile?.type||draft.mediaType||''};bookingWizard(creativeDraft)};
}

async function bookingWizard(draft=creativeDraft){
  const preset=restaurantParam(),restaurants=(await api.list('slots')).filter(row=>row.active!==false),options=restaurants.map(row=>`<option ${row.restaurantKey===preset?'selected':''} value="${esc(row.restaurantKey)}">${esc(row.name)} — ${esc(row.city)}</option>`).join('');
  app.innerHTML=`<main class="shell"><header class="topbar"><div><h1>Book Advertisement Space</h1><p class="muted">Choose a restaurant, placement, duration and creative.</p></div><button class="btn secondary" id="back">Back</button></header><section class="booking-layout"><div class="card"><div class="field"><label>Target restaurant</label><select id="restaurantKey">${options||`<option value="${esc(preset)}">${esc(preset||'No registered restaurant placements yet')}</option>`}</select></div><h3>Available placements</h3><div class="grid slot-grid">${slots.map((slot,index)=>`<article class="card slot ${index===0?'selected':''}" data-slot="${slot.id}"><h3>${slot.name}</h3><p class="muted">${slot.description}</p><p><strong>${money(slot.rate)}</strong> / hour</p></article>`).join('')}</div><div class="field"><label>Select hours</label><select id="hours"><option>1</option><option>3</option><option>6</option><option>12</option><option>24</option><option>48</option></select></div><div class="form-grid"><div class="field"><label>Advertisement title</label><input id="title" value="${esc(draft?.title||'')}" required></div><div class="field"><label>Animation style</label><select id="creativeStyle">${samples.map(row=>`<option value="${row.style}" ${row.style===(draft?.creativeStyle||'spotlight')?'selected':''}>${row.title}</option>`).join('')}</select></div></div><div class="field"><label>Description</label><textarea id="description" required>${esc(draft?.description||'')}</textarea></div><div class="field"><label>Destination URL</label><input id="destinationUrl" type="url" value="${esc(draft?.destinationUrl||'https://g58.in/')}"></div><div class="field"><label>Upload image, GIF or video</label><input id="bookingMedia" type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm"><small class="muted">Optional if already selected in Creative Studio. Maximum 15 MB.</small></div><div class="topbar" style="margin:12px 0 0"><div><span class="muted">Estimated price</span><div class="price" id="estimate"></div></div><button class="btn" id="submit">Send Request</button></div><div class="notice hidden" id="bookingError" role="alert" style="margin-top:14px"></div></div><aside class="card booking-preview"><p class="muted">PLACEMENT PREVIEW</p><div id="bookingCreative" class="ad-preview creative-${esc(draft?.creativeStyle||'spotlight')}">${draft?.mediaUrl?mediaMarkup(draft):'<div class="creative-placeholder"><b>YOUR AD</b><small>Preview updates as you type</small></div>'}</div></aside></section></main>`;
  let selected=slots[0],selectedFile=draft?.mediaFile||null,localUrl=draft?.mediaUrl||'';
  const update=()=>{$('#estimate').textContent=money(selected.rate*Number($('#hours').value));const style=$('#creativeStyle').value;$('#bookingCreative').className=`ad-preview creative-${style}`;$('#bookingCreative').innerHTML=localUrl?mediaMarkup({mediaUrl:localUrl,mediaType:selectedFile?.type||draft?.mediaType,title:$('#title').value}):`<div class="creative-placeholder"><b>${esc($('#title').value||'YOUR AD')}</b><small>${esc($('#description').value||'Add your offer')}</small></div>`};
  $$('[data-slot]').forEach(card=>card.onclick=()=>{$$('[data-slot]').forEach(item=>item.classList.remove('selected'));card.classList.add('selected');selected=slots.find(slot=>slot.id===card.dataset.slot);update()});
  $('#bookingMedia').onchange=event=>{selectedFile=event.target.files[0]||null;if(selectedFile){try{api.validateMediaFile?.(selectedFile)}catch(error){event.target.value='';selectedFile=null;return toast(error.message)}localUrl=URL.createObjectURL(selectedFile)}update()};
  $('#hours').onchange=update;$('#title').oninput=update;$('#description').oninput=update;$('#creativeStyle').onchange=update;update();$('#back').onclick=dashboard;
  $('#submit').onclick=async()=>{const restaurantKey=$('#restaurantKey').value,title=$('#title').value.trim(),description=$('#description').value.trim(),button=$('#submit'),errorBox=$('#bookingError');errorBox.classList.add('hidden');if(!restaurantKey||!title||!description)return toast('Complete all required fields');const hours=Number($('#hours').value);button.disabled=true;button.textContent=selectedFile?'Uploading creative…':'Sending…';try{let media={mediaUrl:draft?.mediaFile?undefined:draft?.mediaUrl||'',mediaType:draft?.mediaType||'',mediaFileId:draft?.mediaFileId||'',mediaName:draft?.mediaName||''};if(selectedFile){const uploaded=await api.uploadAdMedia(selectedFile);media={mediaUrl:uploaded.mediaUrl,mediaType:uploaded.mediaType,mediaFileId:uploaded.fileId,mediaName:uploaded.mediaName}}await api.create('bookings',{customerId:user.$id,customerName:profile?.name||user.name||'Customer',customerEmail:user.email,customerPhone:profile?.phone||'',restaurantKey,slotId:selected.id,hours,rate:selected.rate,amount:selected.rate*hours,title,description,destinationUrl:$('#destinationUrl').value.trim(),creativeStyle:$('#creativeStyle').value,...media,status:'Requested',createdAt:now()});creativeDraft=null;toast('Request sent to Gravity58');await dashboard()}catch(error){const message=error.message||'Could not send request';errorBox.textContent=message;errorBox.classList.remove('hidden');toast(message)}finally{button.disabled=false;button.textContent='Send Request'}};
}

async function paymentProofDialog(id){
  const bookings=await api.list('bookings'),booking=bookings.find(row=>row.id===id);if(!booking)return;
  modal('Submit Payment Proof',`<form id="proofForm"><p class="muted">After completing ${money(booking.amount)}, enter the transaction/reference number. A screenshot is optional.</p><div class="field"><label>Transaction / UTR reference</label><input name="paymentReference" required minlength="4"></div><div class="field"><label>Payment screenshot <small>(optional)</small></label><input name="proofFile" type="file" accept="image/jpeg,image/png,image/webp"></div><div class="field"><label>Note for Gravity58</label><textarea name="paymentNote" placeholder="Optional payment note"></textarea></div><button class="btn full">Submit for Verification</button></form>`,()=>{$('#proofForm').onsubmit=async event=>{event.preventDefault();const form=event.target,fd=new FormData(form),file=fd.get('proofFile'),button=event.submitter;button.disabled=true;button.textContent=file?.size?'Uploading proof…':'Submitting…';try{let proof={};if(file?.size){const uploaded=await api.uploadAdMedia(file);proof={proofMediaUrl:uploaded.mediaUrl,proofMediaType:uploaded.mediaType,proofMediaFileId:uploaded.fileId}}await api.update('bookings',id,{status:'Proof Sent',paymentReference:String(fd.get('paymentReference')).trim(),paymentNote:String(fd.get('paymentNote')||'').trim(),...proof,proofSentAt:now()});closeModal();toast('Payment proof submitted for verification');await dashboard()}catch(error){button.disabled=false;button.textContent='Submit for Verification';toast(error.message||'Could not submit proof')}}})
}

setInterval(()=>$$('[data-expires]').forEach(node=>node.innerHTML=`<strong>${timeLeft(node.dataset.expires)}</strong>`),30000);
boot();
