(function(){
  "use strict";
  const B=window.G58Builder;
  const grid=document.getElementById("templateGrid"),localSection=document.getElementById("localProjects"),localGrid=document.getElementById("localGrid"),toast=document.getElementById("toast");
  let filter="all";
  function notify(message){toast.textContent=message;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2200);}
  function card(spec){return `<article class="template-card" data-kind="${spec.kind}"><div class="template-preview" style="--preview-bg:${spec.bg}"><img src="${spec.image}" alt="${spec.name} website template preview"><span class="preview-browser"></span><div class="preview-copy"><small>${spec.category}</small><strong>${spec.hero}</strong></div><div class="template-badges"><span class="free">FREE</span><span>RESPONSIVE</span></div></div><div class="template-info"><span>${spec.category}</span><h3>${spec.name}</h3><p>${spec.description}</p><div class="template-actions"><a href="preview/?template=${spec.id}" target="_blank">View</a><a class="edit" href="editor/?template=${spec.id}">Edit</a><button class="download" type="button" data-download="${spec.id}">Download</button></div></div></article>`;}
  function renderTemplates(){grid.innerHTML=B.templates.filter(spec=>filter==="all"||spec.kind===filter).map(card).join("");grid.querySelectorAll("[data-download]").forEach(button=>button.onclick=async()=>{button.disabled=true;button.textContent="Preparing…";try{await B.downloadWebsite(B.makeProject(button.dataset.download));notify("Original template downloaded");}finally{button.disabled=false;button.textContent="Download";}});}
  async function renderProjects(){const projects=await B.listProjects();localSection.classList.toggle("hidden",!projects.length);localGrid.innerHTML=projects.map(project=>`<article class="local-card"><span>LAST EDITED · ${new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(project.updatedAt))}</span><h3>${B.escapeHtml(project.name)}</h3><div class="local-card-actions"><a href="editor/?project=${project.id}">Continue Editing</a><button type="button" data-export="${project.id}">Backup</button><button type="button" data-delete="${project.id}">Delete</button></div></article>`).join("");localGrid.querySelectorAll("[data-export]").forEach(button=>button.onclick=()=>B.getProject(button.dataset.export).then(B.exportProject));localGrid.querySelectorAll("[data-delete]").forEach(button=>button.onclick=async()=>{if(!confirm("Delete this local website from this device?"))return;await B.deleteProject(button.dataset.delete);renderProjects();});}
  document.querySelectorAll("[data-filter]").forEach(button=>button.onclick=()=>{filter=button.dataset.filter;document.querySelectorAll("[data-filter]").forEach(row=>row.classList.toggle("active",row===button));renderTemplates();});
  async function importFile(file){try{const project=JSON.parse(await file.text());if(!project?.id||!project?.website?.pages)throw new Error("Invalid project");project.id=B.uid("project");project.updatedAt=new Date().toISOString();await B.saveProject(project);notify("Project imported on this device");await renderProjects();location.href=`editor/?project=${project.id}`;}catch(_error){notify("This is not a valid G58 project file");}}
  document.getElementById("importProject").onchange=event=>event.target.files[0]&&importFile(event.target.files[0]);document.getElementById("importProjectTop").onclick=()=>document.getElementById("importProject").click();
  const dialog=document.getElementById("howDialog");document.getElementById("howButton").onclick=()=>dialog.showModal();dialog.querySelector(".dialog-close").onclick=()=>dialog.close();document.getElementById("dialogStart").onclick=()=>dialog.close();
  renderTemplates();renderProjects();
})();
