const $=(selector,root=document)=>root.querySelector(selector),$$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const app=$('#app'),api=window.Gravity58Ads,now=()=>new Date().toISOString(),money=value=>`₹${Number(value||0).toLocaleString('en-IN')}`;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let user=null,view='overview',data={bookings:[],advertisements:[],profiles:[],slots:[],customers:[],businesses:[],postRows:[],legacyPostDocument:null};
function toast(message){const target=$('#toast');target.textContent=message;target.classList.add('show');setTimeout(()=>target.classList.remove('show'),2200)}
function timeLeft(expiresAt){if(!expiresAt)return'No expiry';const ms=new Date(expiresAt)-new Date();if(ms<=0)return'Expired';const days=Math.floor(ms/864e5),hours=Math.floor(ms%864e5/36e5),minutes=Math.floor(ms%36e5/6e4);return`${days?days+'d ':''}${hours}h ${minutes}m remaining`}
async function boot(){if(!api.configured)return configurationRequired();user=await api.currentUser();if(!user)return login();if(!await api.isTeamAdmin())return accessDenied();await loadData();shell()}
function configurationRequired(){app.innerHTML=`<main class="screen auth"><section class="auth-card glass"><div class="brand"><div class="brand-mark">G</div><div><h2>Gravity58 Team Admin</h2><p class="tagline">Private administration</p></div></div><div class="notice"><strong>Appwrite configuration required</strong><p>Set the project ID and G58 team ID in <code>team-admin/config.js</code>. This portal intentionally has no public or hard-coded administrator password.</p></div><a class="btn full" href="../">Return to G58</a></section></main>`}
function login(){app.innerHTML=`<main class="screen auth"><section class="auth-card glass"><div class="brand"><div class="brand-mark">G</div><div><h2>Gravity58 Team Admin</h2><p class="tagline">G58 team members only</p></div></div><form id="login"><div class="field"><label>Team email</label><input name="email" type="email" required></div><div class="field"><label>Password</label><input name="password" type="password" required></div><button class="btn full">Secure Login</button></form><p class="muted" style="text-align:center">Access is verified through Appwrite team membership.</p></section></main>`;$('#login').onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target));try{await api.login(values.email,values.password);user=await api.currentUser();if(!await api.isTeamAdmin()){await api.logout();throw new Error('This account is not a member of the G58 administration team.')}await loadData();shell()}catch(error){toast(error.message||'Login failed')}}}
function installAdminPasswordRecovery(){
  const form=$('#login');
  if(!form||$('#forgotAdminPassword'))return;
  form.insertAdjacentHTML('afterend','<button class="btn secondary full" id="forgotAdminPassword" type="button" style="margin-top:10px">Forgot password</button>');
  $('#forgotAdminPassword').onclick=()=>modal('Reset Admin Password','<form id="adminRecoveryForm"><div class="field"><label>Admin email</label><input name="email" type="email" required placeholder="you@example.com"></div><button class="btn full">Send Reset Link</button></form>',()=>{$('#adminRecoveryForm').onsubmit=async event=>{event.preventDefault();const button=$('#adminRecoveryForm button');button.disabled=true;button.textContent='Sending…';const values=Object.fromEntries(new FormData(event.target));try{await api.forgotPassword(values.email.trim(),location.origin+'/reset-password/');closeModal();toast('Password reset link sent to your email')}catch(error){button.disabled=false;button.textContent='Send Reset Link';toast(error.message||'Could not send reset link')}}});
}
const renderAdminLogin=login;
login=function(){renderAdminLogin();installAdminPasswordRecovery()};
function accessDenied(){app.innerHTML=`<main class="screen auth"><section class="auth-card glass"><h2>Access denied</h2><p>This signed-in account is not a G58 team member.</p><button class="btn full" id="leave">Sign out</button></section></main>`;$('#leave').onclick=async()=>{await api.logout();user=null;login()}}
async function loadData(){const [bookings,advertisements,profiles,slots,posts]=await Promise.all([api.list('bookings'),api.list('advertisements'),api.list('profiles'),api.list('slots'),api.list('posts')]);const legacy=posts.find(row=>row.recordKey==='global'&&(row.customers||row.businesses));const postRows=posts.filter(row=>row.recordKey!=='global');const customers=[],businesses=[];postRows.forEach(row=>{const post=parsePost(row.payload);if(!post)return;post.userId||=row.userId||'';(row.postType==='business'?businesses:customers).push(post)});data={bookings,advertisements,profiles,slots,postRows,legacyPostDocument:legacy||null,customers:legacy?parse(legacy.customers):customers,businesses:legacy?parse(legacy.businesses):businesses}}
function parse(value){try{return Array.isArray(value)?value:JSON.parse(value||'[]')}catch{return[]}}
function parsePost(value){try{return typeof value==='string'?JSON.parse(value):value}catch{return null}}
function shell(){app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">G</div><div><strong>Gravity58</strong><small class="muted">Team Administration</small></div></div><nav class="nav">${nav('overview','◉','Overview')}${nav('bookings','▣','Ad Bookings')}${nav('campaigns','✦','Campaigns')}${nav('marketplace','⌘','Public Posts')}${nav('accounts','◎','Accounts')}${nav('slots','▦','Ad Placements')}<button id="logout">⇥ Logout</button></nav></aside><main class="main"><header class="topbar"><strong>Private Gravity58 Team Portal</strong><span class="status-pill"><span class="dot"></span>${esc(user.email)}</span></header><section class="content" id="page"></section></main></div>`;$$('[data-view]').forEach(button=>button.onclick=()=>{view=button.dataset.view;shell()});$('#logout').onclick=async()=>{await api.logout();user=null;login()};renderView()}
function nav(key,icon,label){return`<button data-view="${key}" class="${view===key?'active':''}"><span>${icon}</span>${label}</button>`}
function renderView(){({overview,bookings,campaigns,marketplace,accounts,slots}[view]||overview)()}
function metric(title,value){return`<article class="metric"><span>${title}</span><strong>${value}</strong></article>`}
function overview(){const revenue=data.bookings.filter(row=>['Live','Expired'].includes(row.status)).reduce((sum,row)=>sum+Number(row.amount||0),0);$('#page').innerHTML=`<div class="section-head"><div><h1>Unified Administration</h1><p class="muted">Manage advertising, public posts, accounts and restaurant placements from one G58-only portal.</p></div><button class="btn" id="refresh">Refresh</button></div><div class="grid stats">${metric('Pending Bookings',data.bookings.filter(row=>['Requested','Proof Sent'].includes(row.status)).length)}${metric('Live Ads',data.advertisements.filter(row=>row.active&&(!row.expiresAt||new Date(row.expiresAt)>new Date())).length)}${metric('Public Posts',data.customers.length+data.businesses.length)}${metric('Booked Revenue',money(revenue))}</div><div class="section-head"><h2>Quick actions</h2></div><div class="grid restaurant-grid"><button class="card admin-action" data-open="bookings"><h3>Review bookings</h3><p>Send payment links and activate paid campaigns.</p></button><button class="card admin-action" data-open="campaigns"><h3>Campaign timers</h3><p>Pause, publish or remove restaurant ads.</p></button><button class="card admin-action" data-open="marketplace"><h3>Moderate posts</h3><p>Review customer posts and business cards.</p></button></div>`;$('#refresh').onclick=refresh;$$('[data-open]').forEach(button=>button.onclick=()=>{view=button.dataset.open;shell()})}
function bookings(){$('#page').innerHTML=`<div class="section-head"><div><h1>Advertising Bookings</h1><p class="muted">Payment and activation workflow.</p></div><button class="btn" id="refresh">Refresh</button></div><div class="card table-wrap"><table><thead><tr><th>Customer</th><th>Restaurant / Placement</th><th>Duration</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody>${data.bookings.map(bookingRow).join('')||'<tr><td colspan="6">No requests.</td></tr>'}</tbody></table></div>`;$('#refresh').onclick=refresh;bindBookingActions()}
function bookingRow(row){let actions='';if(row.status==='Requested')actions=`<button class="btn small" data-payment="${row.id}">Payment link</button><button class="btn small red" data-reject="${row.id}">Reject</button>`;else if(row.status==='Proof Sent')actions=`<button class="btn small green" data-activate="${row.id}">Confirm & activate</button><button class="btn small red" data-reject="${row.id}">Reject</button>`;else if(row.status==='Live')actions=`<button class="btn small secondary" data-stop="${row.id}">Stop</button>`;else actions='<span class="muted">No action</span>';return`<tr><td><strong>${esc(row.customerName||'Customer')}</strong><br><small>${esc(row.customerEmail||'')}</small></td><td>${esc(row.restaurantKey)}<br><small>${esc(row.slotId)}</small></td><td>${row.hours}h</td><td>${money(row.amount)}</td><td>${esc(row.status)}${row.expiresAt?`<br><small data-expires="${row.expiresAt}">${timeLeft(row.expiresAt)}</small>`:''}</td><td><div class="actions">${actions}</div></td></tr>`}
function bindBookingActions(){$$('[data-payment]').forEach(button=>button.onclick=()=>paymentDialog(button.dataset.payment));$$('[data-reject]').forEach(button=>button.onclick=()=>changeBooking(button.dataset.reject,{status:'Rejected',adminMessage:'The Gravity58 team rejected this booking request.'}));$$('[data-activate]').forEach(button=>button.onclick=()=>activationDialog(button.dataset.activate));$$('[data-stop]').forEach(button=>button.onclick=()=>stopBooking(button.dataset.stop))}
function paymentDialog(id){const row=data.bookings.find(item=>item.id===id);modal('Send Payment Link',`<form id="payForm"><p><strong>${esc(row.customerName)}</strong> requested ${row.hours} hour(s).</p><div class="field"><label>Payment link</label><input name="paymentLink" type="url" required placeholder="Razorpay payment link"></div><div class="field"><label>Message</label><textarea name="adminMessage">Pay ${money(row.amount)} using this secure link. Send the screenshot after payment.</textarea></div><button class="btn full">Send to customer portal</button></form>`,()=>{$('#payForm').onsubmit=async event=>{event.preventDefault();await changeBooking(id,{...Object.fromEntries(new FormData(event.target)),status:'Payment Link Sent',paymentLinkSentAt:now()},false);closeModal();await refresh()}})}
function activationDialog(id){const row=data.bookings.find(item=>item.id===id);modal('Activate Campaign',`<form id="activateForm"><p>Target: <strong>${esc(row.restaurantKey)}</strong> for <strong>${row.hours} hour(s)</strong>.</p><div class="field"><label>Icon / image URL</label><input name="image" value="📣"></div><div class="field"><label>Button label</label><input name="buttonLabel" value="View Offer"></div><div class="field"><label>Destination URL</label><input name="destinationUrl" value="${esc(row.destinationUrl||'https://g58.in/')}"></div><div class="field"><label>Confirmation message</label><textarea name="adminMessage">Payment confirmed. Your advertisement is live.</textarea></div><button class="btn green full">Activate advertisement</button></form>`,()=>{$('#activateForm').onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target)),start=new Date(),expires=new Date(start.getTime()+Number(row.hours)*36e5);await api.update('bookings',id,{status:'Live',...values,activatedAt:start.toISOString(),expiresAt:expires.toISOString()});await api.create('advertisements',{bookingId:id,restaurantKey:row.restaurantKey,slotId:row.slotId,title:row.title,description:row.description,image:values.image,buttonLabel:values.buttonLabel,destinationUrl:values.destinationUrl,amount:Number(row.amount),hours:Number(row.hours),active:true,status:'Live',activatedAt:start.toISOString(),expiresAt:expires.toISOString()});closeModal();await refresh();toast('Advertisement activated')}})}
async function changeBooking(id,changes,rerender=true){await api.update('bookings',id,changes);if(rerender)await refresh()}
async function stopBooking(id){const booking=data.bookings.find(row=>row.id===id);await api.update('bookings',id,{status:'Expired'});const ad=data.advertisements.find(row=>row.bookingId===booking.id);if(ad)await api.update('advertisements',ad.id,{active:false,status:'Stopped'});await refresh()}
function campaigns(){$('#page').innerHTML=`<div class="section-head"><div><h1>Published Campaigns</h1><p class="muted">Every card shows the remaining booked time.</p></div><button class="btn" id="manualCampaign">+ Manual campaign</button></div><div class="grid restaurant-grid">${data.advertisements.map(adCard).join('')||'<div class="empty">No campaigns.</div>'}</div>`;$('#manualCampaign').onclick=manualCampaign;$$('[data-toggle]').forEach(button=>button.onclick=()=>toggleCampaign(button.dataset.toggle));$$('[data-delete]').forEach(button=>button.onclick=()=>deleteCampaign(button.dataset.delete))}
function adCard(ad){return`<article class="card"><div class="ad-icon">${esc(ad.image||'📣')}</div><h3>${esc(ad.title)}</h3><p class="muted">${esc(ad.restaurantKey)}</p><p>${esc(ad.description||'')}</p><div class="chips"><span class="chip">${ad.active?'Live':esc(ad.status||'Paused')}</span><span class="chip" data-expires="${ad.expiresAt||''}">${timeLeft(ad.expiresAt)}</span></div><div class="actions"><button class="btn small" data-toggle="${ad.id}">${ad.active?'Pause':'Publish'}</button><button class="btn small red" data-delete="${ad.id}">Delete</button></div></article>`}
async function toggleCampaign(id){const ad=data.advertisements.find(row=>row.id===id);await api.update('advertisements',id,{active:!ad.active,status:!ad.active?'Live':'Paused'});await refresh()}
async function deleteCampaign(id){if(!confirm('Permanently delete this campaign?'))return;await api.remove('advertisements',id);await refresh()}
function manualCampaign(){modal('Manual Advertisement',`<form id="manualForm"><div class="field"><label>Restaurant placement</label><select name="restaurantKey">${data.slots.map(row=>`<option value="${esc(row.restaurantKey)}">${esc(row.name)} — ${esc(row.city)}</option>`).join('')}</select></div><div class="field"><label>Placement</label><select name="slotId"><option value="right_rail">Right menu rail</option><option value="preparing">Preparing screen</option><option value="thankyou">Thank-you screen</option></select></div><div class="field"><label>Title</label><input name="title" required></div><div class="field"><label>Description</label><textarea name="description" required></textarea></div><div class="field"><label>Hours</label><input name="hours" type="number" min="1" value="1"></div><div class="field"><label>Destination URL</label><input name="destinationUrl" value="https://g58.in/"></div><button class="btn full">Publish campaign</button></form>`,()=>{$('#manualForm').onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target)),start=new Date(),expires=new Date(start.getTime()+Number(values.hours)*36e5);await api.create('advertisements',{...values,image:'📣',buttonLabel:'View Offer',hours:Number(values.hours),active:true,status:'Live',activatedAt:start.toISOString(),expiresAt:expires.toISOString()});closeModal();await refresh()}})}
function marketplace(){$('#page').innerHTML=`<div class="section-head"><div><h1>Public Posts & Business Cards</h1><p class="muted">Edit records or select multiple entries for permanent deletion.</p></div><button class="btn red" id="deleteSelected">Delete selected</button></div><div class="tabs"><button class="btn small" data-market="customer">Customer posts (${data.customers.length})</button><button class="btn small secondary" data-market="business">Business cards (${data.businesses.length})</button></div><div class="card table-wrap" id="marketTable" style="margin-top:14px"></div>`;let type='customer';const draw=()=>{const rows=type==='customer'?data.customers:data.businesses;$('#marketTable').innerHTML=`<table><thead><tr><th></th><th>Title</th><th>Location</th><th>Account</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(row=>`<tr><td><input type="checkbox" data-post-id="${esc(row.id)}"></td><td>${esc(row.title)}</td><td>${esc(row.district||row.city||'')}</td><td>${esc(row.accountEmail||row.email||'')}</td><td>${row.blocked?'Blocked':'Active'}</td><td><button class="btn small" data-edit-post="${esc(row.id)}">Edit</button></td></tr>`).join('')||'<tr><td colspan="6">No records.</td></tr>'}</tbody></table>`;$$('[data-edit-post]').forEach(button=>button.onclick=()=>editPost(type,button.dataset.editPost))};draw();$$('[data-market]').forEach(button=>button.onclick=()=>{type=button.dataset.market;$$('[data-market]').forEach(item=>item.className='btn small secondary');button.className='btn small';draw()});$('#deleteSelected').onclick=async()=>{const ids=$$('[data-post-id]:checked').map(input=>input.dataset.postId);if(!ids.length||!confirm(`Delete ${ids.length} selected record(s)?`))return;if(type==='customer')data.customers=data.customers.filter(row=>!ids.includes(row.id));else data.businesses=data.businesses.filter(row=>!ids.includes(row.id));await savePosts();marketplace()}}
function editPost(type,id){const post=(type==='customer'?data.customers:data.businesses).find(row=>String(row.id)===String(id));if(!post)return;modal('Edit Public Record',`<form id="editPostForm"><div class="field"><label>Title</label><input name="title" value="${esc(post.title||'')}" required></div><div class="field"><label>Description</label><textarea name="description" required>${esc(post.description||'')}</textarea></div><div class="form-grid"><div class="field"><label>State</label><input name="state" value="${esc(post.state||'')}"></div><div class="field"><label>District / City</label><input name="district" value="${esc(post.district||post.city||'')}"></div></div><button class="btn full">Save Changes</button></form>`,()=>{$('#editPostForm').onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target));Object.assign(post,values,{city:values.district});await savePost(post,type);closeModal();marketplace();toast('Public record updated')}})}
async function savePost(post,type){if(data.legacyPostDocument)return savePosts();const row=data.postRows.find(item=>String(item.recordKey)===String(post.id));if(!row)throw new Error('Appwrite post row not found');const updated=await api.update('posts',row.id,{postType:type,userId:row.userId||post.userId||'',payload:JSON.stringify(post),updatedAt:now()});Object.assign(row,updated)}
async function savePosts(){if(data.legacyPostDocument){await api.update('posts',data.legacyPostDocument.id,{recordKey:'global',customers:JSON.stringify(data.customers),businesses:JSON.stringify(data.businesses),updatedAt:now()});return}const desired=new Set([...data.customers,...data.businesses].map(post=>String(post.id)));for(const row of [...data.postRows]){if(!desired.has(String(row.recordKey))){await api.remove('posts',row.id);data.postRows=data.postRows.filter(item=>item.id!==row.id)}}}
function accounts(){$('#page').innerHTML=`<div class="section-head"><div><h1>Advertising Accounts</h1><p class="muted">Block profiles from posting or booking. Authentication-account deletion requires the protected Appwrite admin function.</p></div></div><div class="card table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Location</th><th>Status</th><th>Action</th></tr></thead><tbody>${data.profiles.map(row=>`<tr><td>${esc(row.name||'')}</td><td>${esc(row.email||'')}</td><td>${esc(row.phone||'')}</td><td>${esc([row.district,row.state].filter(Boolean).join(', '))}</td><td>${row.blocked?'Blocked':'Active'}</td><td><button class="btn small ${row.blocked?'green':'red'}" data-block="${row.id}">${row.blocked?'Unblock':'Block'}</button></td></tr>`).join('')||'<tr><td colspan="6">No profiles.</td></tr>'}</tbody></table></div>`;$$('[data-block]').forEach(button=>button.onclick=async()=>{const row=data.profiles.find(item=>item.id===button.dataset.block);await api.update('profiles',row.id,{blocked:!row.blocked});await refresh()})}
function slots(){$('#page').innerHTML=`<div class="section-head"><div><h1>Restaurant Ad Placements</h1><p class="muted">Restaurant operational data stays local; only these ad targeting keys are stored here.</p></div></div><div class="grid restaurant-grid">${data.slots.map(row=>`<article class="card"><h3>${esc(row.name)}</h3><p>${esc(row.city)}</p><code>${esc(row.restaurantKey)}</code><div class="chips"><span class="chip">${row.active?'Active':'Paused'}</span></div></article>`).join('')||'<div class="empty">No registered placements.</div>'}</div>`}
async function refresh(){await loadData();shell()}
function modal(title,body,ready){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><section class="modal"><div class="section-head"><h2>${title}</h2><button class="btn small secondary" id="close">✕</button></div>${body}</section></div>`);$('#close').onclick=closeModal;ready?.()}
function closeModal(){$('#modal')?.remove()}
setInterval(()=>$$('[data-expires]').forEach(node=>node.textContent=timeLeft(node.dataset.expires)),30000);
boot();
